name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        # Generate package-lock.json if it doesn't exist
        if [ ! -f package-lock.json ]; then
          npm install
        else
          npm ci
        fi
      
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT || '22' }}
        script: |
          cd /var/www/cmms-ui
          git pull origin main
          
          # Handle package-lock.json
          if [ ! -f package-lock.json ]; then
            npm install --production
          else
            npm ci --production
          fi
          
          npm run build
          
          # Restart or start the application
          if pm2 list | grep -q cmms-ui; then
            pm2 restart cmms-ui
          else
            pm2 start npm --name "cmms-ui" -- start -- -p 8000
          fi
