name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT || '22' }}
        script: |
          # Pastikan Node.js & PM2 sudah ada
          if ! command -v pm2 &> /dev/null
          then
            echo "Installing PM2..."
            npm install -g pm2
          fi

          # Kalau folder project belum ada → clone repo
          if [ ! -d "/var/www/cmms-ui/.git" ]; then
            mkdir -p /var/www
            cd /var/www
            git clone git@github.com:${{ github.repository }} cmms-ui
            cd cmms-ui
          else
            cd /var/www/cmms-ui
            git pull origin main
          fi

          # Install dependencies
          npm install --production

          # Build
          npm run build

          # Start or restart with PM2
          if pm2 list | grep -q cmms-ui; then
            pm2 restart cmms-ui --update-env
          else
            pm2 start npm --name "cmms-ui" -- start -- -p 8000
          fi

          # Save PM2 process list
          pm2 save

