name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Generate package-lock.json
      run: |
        chmod +x ./scripts/generate-package-lock.sh
        ./scripts/generate-package-lock.sh
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT || '22' }}
        script: |
          cd /var/www/cmms-ui
          git pull origin main
          
          # Ensure we have the latest package-lock.json
          npm install --package-lock-only
          
          # Install production dependencies
          npm ci --production
          
          # Build the application
          npm run build
          
          # Restart or start the application
          if pm2 list | grep -q cmms-ui; then
            pm2 restart cmms-ui --update-env
          else
            pm2 start npm --name "cmms-ui" -- start -- -p 8000
          fi
          
          # Save PM2 process list
          pm2 save
