name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Copy build folder to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT || '22' }}
        source: "build/*"
        target: "/var/www/cmms-ui/build"
    
    - name: Deploy with PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT || '22' }}
        script: |
          cd /var/www/cmms-ui

          # Install PM2 kalau belum ada
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # Start / Restart dengan PM2 serve (karena hasil build static React)
          if pm2 list | grep -q cmms-ui; then
            pm2 restart cmms-ui --update-env
          else
            pm2 serve build 8000 --name "cmms-ui" --spa
          fi

          pm2 save
